package google

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/oauth2"
)

// OutboundMessage is the header/body material the send_delivery handler
// resolved deterministically: From from the thread's mailbox (never
// model-chosen), To = last inbound sender, In-Reply-To = last message-id,
// References = the thread's message-id chain, MessageID = the self-chosen
// <sb-...> id persisted BEFORE the send (invariant 5 seam).
type OutboundMessage struct {
	From, To, Subject, Body, MessageID, InReplyTo string
	References                                    []string
	Date                                          time.Time
}

// aiAttributionMarkers are scrubbed from outbound bodies (invariant 6 belt —
// draft_delivery scrubs at write time too).
var aiAttributionMarkers = []string{"co-authored-by:", "generated with", "generated by claude", "🤖"}

// ScrubAIAttribution removes lines carrying AI attribution markers.
func ScrubAIAttribution(body string) string {
	lines := strings.Split(body, "\n")
	out := lines[:0]
	for _, line := range lines {
		lower := strings.ToLower(line)
		drop := false
		for _, m := range aiAttributionMarkers {
			if strings.Contains(lower, m) {
				drop = true
				break
			}
		}
		if !drop {
			out = append(out, line)
		}
	}
	return strings.TrimRight(strings.Join(out, "\n"), "\n")
}

// BuildOutboundMIME assembles a text/plain UTF-8 RFC 2822 message.
func BuildOutboundMIME(msg OutboundMessage) ([]byte, error) {
	if msg.From == "" || msg.To == "" {
		return nil, fmt.Errorf("outbound message requires From and To")
	}
	if msg.MessageID == "" {
		return nil, fmt.Errorf("outbound message requires a self-chosen Message-ID")
	}
	date := msg.Date
	if date.IsZero() {
		date = time.Now()
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "From: %s\r\n", msg.From)
	fmt.Fprintf(&b, "To: %s\r\n", msg.To)
	if msg.Subject != "" {
		fmt.Fprintf(&b, "Subject: %s\r\n", msg.Subject)
	}
	fmt.Fprintf(&b, "Date: %s\r\n", date.Format(time.RFC1123Z))
	fmt.Fprintf(&b, "Message-ID: %s\r\n", msg.MessageID)
	if msg.InReplyTo != "" {
		fmt.Fprintf(&b, "In-Reply-To: %s\r\n", msg.InReplyTo)
	}
	if len(msg.References) > 0 {
		fmt.Fprintf(&b, "References: %s\r\n", strings.Join(msg.References, " "))
	}
	b.WriteString("MIME-Version: 1.0\r\n")
	b.WriteString("Content-Type: text/plain; charset=\"UTF-8\"\r\n")
	b.WriteString("\r\n")
	b.WriteString(ScrubAIAttribution(msg.Body))
	b.WriteString("\r\n")
	return b.Bytes(), nil
}

// AccountSender is the production send adapter: it resolves the from-account
// row by email, builds the per-account authorized client from the stored
// refresh token, and posts via GmailSender. Wired into the tools seam by cmd/*.
type AccountSender struct {
	Pool     *pgxpool.Pool
	OAuthCfg *oauth2.Config
	TokenKey string
	BaseURL  string
}

func (a *AccountSender) Send(ctx context.Context, fromUserID string, rawMIME []byte, threadID string) (string, error) {
	var acct Account
	err := a.Pool.QueryRow(ctx,
		`SELECT id, account_email, calendar_in_availability FROM source_accounts
		 WHERE provider='google' AND lower(account_email)=lower($1)`, fromUserID).
		Scan(&acct.ID, &acct.Email, &acct.CalendarInAvailability)
	if err != nil {
		return "", fmt.Errorf("resolve send account %s: %w", fromUserID, err)
	}
	hc, err := TokenClient(ctx, a.Pool, a.OAuthCfg, acct, a.TokenKey)
	if err != nil {
		return "", err
	}
	return NewGmailSender(hc, a.BaseURL).Send(ctx, acct.Email, rawMIME, threadID)
}

// SendRejectedError is a DEFINITE API rejection (non-2xx): the message was
// not accepted, so retry is safe. Transport errors stay untyped — the send
// may have gone through, and invariant 4 errs toward never-resend.
type SendRejectedError struct {
	Status int
	Body   string
}

func (e *SendRejectedError) Error() string {
	return fmt.Sprintf("gmail send HTTP %d: %s", e.Status, e.Body)
}

// GmailSender posts raw MIME to users.messages.send.
type GmailSender struct {
	hc      *http.Client
	baseURL string
}

func NewGmailSender(hc *http.Client, baseURL string) *GmailSender {
	if baseURL == "" {
		baseURL = "https://gmail.googleapis.com"
	}
	return &GmailSender{hc: hc, baseURL: strings.TrimRight(baseURL, "/")}
}

// Send posts {raw: base64url(mime), threadId} and returns the API message id.
func (s *GmailSender) Send(ctx context.Context, userID string, rawMIME []byte, threadID string) (string, error) {
	payload := map[string]string{"raw": base64.RawURLEncoding.EncodeToString(rawMIME)}
	if threadID != "" {
		payload["threadId"] = threadID
	}
	body, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("marshal send payload: %w", err)
	}

	u := s.baseURL + "/gmail/v1/users/" + url.PathEscape(userID) + "/messages/send"
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, u, bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("build send request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := s.hc.Do(req)
	if err != nil {
		return "", fmt.Errorf("gmail send: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return "", fmt.Errorf("read send response: %w", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		// A definite rejection: Google did NOT accept the message, so the
		// caller may safely clear the reserved Message-ID and allow a retry.
		return "", &SendRejectedError{Status: resp.StatusCode, Body: string(respBody[:min(300, len(respBody))])}
	}
	var out struct {
		ID string `json:"id"`
	}
	if err := json.Unmarshal(respBody, &out); err != nil {
		return "", fmt.Errorf("parse send response: %w", err)
	}
	return out.ID, nil
}
